---
# 3. Ingress Gateway
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  releaseName: istio-ingress
  targetNamespace: istio-system
  interval: 1m
  chart:
    spec:
      chart: gateway
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
