---
# 1. Base
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  releaseName: istio-base
  targetNamespace: istio-system
  interval: 1m
  chart:
    spec:
      chart: base
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  upgrade:
    crds: CreateReplace
